//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 12:56:42 PM IST 
//


package com.hdfcbank.xsd.otpval.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DemoGraphicDtlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DemoGraphicDtlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PIDtlsAvailable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PIDtls" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}PIDtlsType" minOccurs="0"/&gt;
 *         &lt;element name="PADtlsAvailable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PADtls" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}PADtlsType" minOccurs="0"/&gt;
 *         &lt;element name="PFADtlsAvailable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PFADtls" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}PFADtlsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DemoGraphicDtlType", propOrder = {
    "lang",
    "piDtlsAvailable",
    "piDtls",
    "paDtlsAvailable",
    "paDtls",
    "pfaDtlsAvailable",
    "pfaDtls"
})
public class DemoGraphicDtlType {

    protected String lang;
    @XmlElement(name = "PIDtlsAvailable")
    protected String piDtlsAvailable;
    @XmlElement(name = "PIDtls")
    protected PIDtlsType piDtls;
    @XmlElement(name = "PADtlsAvailable")
    protected String paDtlsAvailable;
    @XmlElement(name = "PADtls")
    protected PADtlsType paDtls;
    @XmlElement(name = "PFADtlsAvailable")
    protected String pfaDtlsAvailable;
    @XmlElement(name = "PFADtls")
    protected PFADtlsType pfaDtls;

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the piDtlsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIDtlsAvailable() {
        return piDtlsAvailable;
    }

    /**
     * Sets the value of the piDtlsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIDtlsAvailable(String value) {
        this.piDtlsAvailable = value;
    }

    /**
     * Gets the value of the piDtls property.
     * 
     * @return
     *     possible object is
     *     {@link PIDtlsType }
     *     
     */
    public PIDtlsType getPIDtls() {
        return piDtls;
    }

    /**
     * Sets the value of the piDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIDtlsType }
     *     
     */
    public void setPIDtls(PIDtlsType value) {
        this.piDtls = value;
    }

    /**
     * Gets the value of the paDtlsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPADtlsAvailable() {
        return paDtlsAvailable;
    }

    /**
     * Sets the value of the paDtlsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPADtlsAvailable(String value) {
        this.paDtlsAvailable = value;
    }

    /**
     * Gets the value of the paDtls property.
     * 
     * @return
     *     possible object is
     *     {@link PADtlsType }
     *     
     */
    public PADtlsType getPADtls() {
        return paDtls;
    }

    /**
     * Sets the value of the paDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link PADtlsType }
     *     
     */
    public void setPADtls(PADtlsType value) {
        this.paDtls = value;
    }

    /**
     * Gets the value of the pfaDtlsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFADtlsAvailable() {
        return pfaDtlsAvailable;
    }

    /**
     * Sets the value of the pfaDtlsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFADtlsAvailable(String value) {
        this.pfaDtlsAvailable = value;
    }

    /**
     * Gets the value of the pfaDtls property.
     * 
     * @return
     *     possible object is
     *     {@link PFADtlsType }
     *     
     */
    public PFADtlsType getPFADtls() {
        return pfaDtls;
    }

    /**
     * Sets the value of the pfaDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link PFADtlsType }
     *     
     */
    public void setPFADtls(PFADtlsType value) {
        this.pfaDtls = value;
    }

}
