//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 12:56:42 PM IST 
//


package com.hdfcbank.xsd.otpval.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="REQ_TYPE" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}reqType"/&gt;
 *         &lt;element name="ResidentConsent" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}ResidentConsentType"/&gt;
 *         &lt;element name="UID_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OTP" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}otpType" minOccurs="0"/&gt;
 *         &lt;element name="BIO" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}bioType" minOccurs="0"/&gt;
 *         &lt;element name="DemoGraphicDtl" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}DemoGraphicDtlType" minOccurs="0"/&gt;
 *         &lt;element name="Req_Date_Time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Req_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Cost_Center_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Meta" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}metaType" minOccurs="0"/&gt;
 *         &lt;element name="Auth" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}authType" minOccurs="0"/&gt;
 *         &lt;element name="TransactionInfo" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}TransactionInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Cert_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Value1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Value2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOAStandardElements" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}soastandarddtls" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reqtype",
    "residentConsent",
    "uidno",
    "otp",
    "bio",
    "demoGraphicDtl",
    "reqDateTime",
    "reqNo",
    "costCenterNo",
    "meta",
    "auth",
    "transactionInfo",
    "certName",
    "value1",
    "value2",
    "soaStandardElements"
})
@XmlRootElement(name = "eKYCRequest")
public class EKYCRequest {

    @XmlElement(name = "REQ_TYPE", required = true)
    @XmlSchemaType(name = "string")
    protected ReqType reqtype;
    @XmlElement(name = "ResidentConsent", required = true)
    protected ResidentConsentType residentConsent;
    @XmlElement(name = "UID_NO", required = true)
    protected String uidno;
    @XmlElement(name = "OTP")
    protected OtpType otp;
    @XmlElement(name = "BIO")
    protected BioType bio;
    @XmlElement(name = "DemoGraphicDtl")
    protected DemoGraphicDtlType demoGraphicDtl;
    @XmlElement(name = "Req_Date_Time")
    protected String reqDateTime;
    @XmlElement(name = "Req_No")
    protected String reqNo;
    @XmlElement(name = "Cost_Center_No")
    protected String costCenterNo;
    @XmlElement(name = "Meta")
    protected MetaType meta;
    @XmlElement(name = "Auth")
    protected AuthType auth;
    @XmlElement(name = "TransactionInfo")
    protected TransactionInfoType transactionInfo;
    @XmlElement(name = "Cert_Name")
    protected String certName;
    @XmlElement(name = "Value1")
    protected String value1;
    @XmlElement(name = "Value2")
    protected String value2;
    @XmlElement(name = "SOAStandardElements")
    protected Soastandarddtls soaStandardElements;

    /**
     * Gets the value of the reqtype property.
     * 
     * @return
     *     possible object is
     *     {@link ReqType }
     *     
     */
    public ReqType getREQTYPE() {
        return reqtype;
    }

    /**
     * Sets the value of the reqtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReqType }
     *     
     */
    public void setREQTYPE(ReqType value) {
        this.reqtype = value;
    }

    /**
     * Gets the value of the residentConsent property.
     * 
     * @return
     *     possible object is
     *     {@link ResidentConsentType }
     *     
     */
    public ResidentConsentType getResidentConsent() {
        return residentConsent;
    }

    /**
     * Sets the value of the residentConsent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidentConsentType }
     *     
     */
    public void setResidentConsent(ResidentConsentType value) {
        this.residentConsent = value;
    }

    /**
     * Gets the value of the uidno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIDNO() {
        return uidno;
    }

    /**
     * Sets the value of the uidno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIDNO(String value) {
        this.uidno = value;
    }

    /**
     * Gets the value of the otp property.
     * 
     * @return
     *     possible object is
     *     {@link OtpType }
     *     
     */
    public OtpType getOTP() {
        return otp;
    }

    /**
     * Sets the value of the otp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtpType }
     *     
     */
    public void setOTP(OtpType value) {
        this.otp = value;
    }

    /**
     * Gets the value of the bio property.
     * 
     * @return
     *     possible object is
     *     {@link BioType }
     *     
     */
    public BioType getBIO() {
        return bio;
    }

    /**
     * Sets the value of the bio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioType }
     *     
     */
    public void setBIO(BioType value) {
        this.bio = value;
    }

    /**
     * Gets the value of the demoGraphicDtl property.
     * 
     * @return
     *     possible object is
     *     {@link DemoGraphicDtlType }
     *     
     */
    public DemoGraphicDtlType getDemoGraphicDtl() {
        return demoGraphicDtl;
    }

    /**
     * Sets the value of the demoGraphicDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemoGraphicDtlType }
     *     
     */
    public void setDemoGraphicDtl(DemoGraphicDtlType value) {
        this.demoGraphicDtl = value;
    }

    /**
     * Gets the value of the reqDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqDateTime() {
        return reqDateTime;
    }

    /**
     * Sets the value of the reqDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqDateTime(String value) {
        this.reqDateTime = value;
    }

    /**
     * Gets the value of the reqNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqNo() {
        return reqNo;
    }

    /**
     * Sets the value of the reqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqNo(String value) {
        this.reqNo = value;
    }

    /**
     * Gets the value of the costCenterNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterNo() {
        return costCenterNo;
    }

    /**
     * Sets the value of the costCenterNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterNo(String value) {
        this.costCenterNo = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link MetaType }
     *     
     */
    public MetaType getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaType }
     *     
     */
    public void setMeta(MetaType value) {
        this.meta = value;
    }

    /**
     * Gets the value of the auth property.
     * 
     * @return
     *     possible object is
     *     {@link AuthType }
     *     
     */
    public AuthType getAuth() {
        return auth;
    }

    /**
     * Sets the value of the auth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthType }
     *     
     */
    public void setAuth(AuthType value) {
        this.auth = value;
    }

    /**
     * Gets the value of the transactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionInfoType }
     *     
     */
    public TransactionInfoType getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * Sets the value of the transactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionInfoType }
     *     
     */
    public void setTransactionInfo(TransactionInfoType value) {
        this.transactionInfo = value;
    }

    /**
     * Gets the value of the certName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertName() {
        return certName;
    }

    /**
     * Sets the value of the certName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertName(String value) {
        this.certName = value;
    }

    /**
     * Gets the value of the value1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue1() {
        return value1;
    }

    /**
     * Sets the value of the value1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue1(String value) {
        this.value1 = value;
    }

    /**
     * Gets the value of the value2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue2() {
        return value2;
    }

    /**
     * Sets the value of the value2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue2(String value) {
        this.value2 = value;
    }

    /**
     * Gets the value of the soaStandardElements property.
     * 
     * @return
     *     possible object is
     *     {@link Soastandarddtls }
     *     
     */
    public Soastandarddtls getSOAStandardElements() {
        return soaStandardElements;
    }

    /**
     * Sets the value of the soaStandardElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Soastandarddtls }
     *     
     */
    public void setSOAStandardElements(Soastandarddtls value) {
        this.soaStandardElements = value;
    }

}
