//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 12:56:42 PM IST 
//


package com.hdfcbank.xsd.otpval.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for soastandarddtls complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="soastandarddtls"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="service_user" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="service_password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="consumer_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ADVappId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ADVappName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filler8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "soastandarddtls", propOrder = {
    "serviceUser",
    "servicePassword",
    "consumerName",
    "adVappId",
    "adVappName",
    "filler1",
    "filler2",
    "filler3",
    "filler4",
    "filler5",
    "filler6",
    "filler7",
    "filler8"
})
public class Soastandarddtls {

    @XmlElement(name = "service_user")
    protected String serviceUser;
    @XmlElement(name = "service_password")
    protected String servicePassword;
    @XmlElement(name = "consumer_name")
    protected String consumerName;
    @XmlElement(name = "ADVappId")
    protected String adVappId;
    @XmlElement(name = "ADVappName")
    protected String adVappName;
    protected String filler1;
    protected String filler2;
    protected String filler3;
    protected String filler4;
    protected String filler5;
    protected String filler6;
    protected String filler7;
    protected String filler8;

    /**
     * Gets the value of the serviceUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceUser() {
        return serviceUser;
    }

    /**
     * Sets the value of the serviceUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceUser(String value) {
        this.serviceUser = value;
    }

    /**
     * Gets the value of the servicePassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicePassword() {
        return servicePassword;
    }

    /**
     * Sets the value of the servicePassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicePassword(String value) {
        this.servicePassword = value;
    }

    /**
     * Gets the value of the consumerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * Sets the value of the consumerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerName(String value) {
        this.consumerName = value;
    }

    /**
     * Gets the value of the adVappId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADVappId() {
        return adVappId;
    }

    /**
     * Sets the value of the adVappId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADVappId(String value) {
        this.adVappId = value;
    }

    /**
     * Gets the value of the adVappName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADVappName() {
        return adVappName;
    }

    /**
     * Sets the value of the adVappName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADVappName(String value) {
        this.adVappName = value;
    }

    /**
     * Gets the value of the filler1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller1() {
        return filler1;
    }

    /**
     * Sets the value of the filler1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller1(String value) {
        this.filler1 = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller2(String value) {
        this.filler2 = value;
    }

    /**
     * Gets the value of the filler3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * Sets the value of the filler3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller3(String value) {
        this.filler3 = value;
    }

    /**
     * Gets the value of the filler4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller4() {
        return filler4;
    }

    /**
     * Sets the value of the filler4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller4(String value) {
        this.filler4 = value;
    }

    /**
     * Gets the value of the filler5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller5() {
        return filler5;
    }

    /**
     * Sets the value of the filler5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller5(String value) {
        this.filler5 = value;
    }

    /**
     * Gets the value of the filler6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller6() {
        return filler6;
    }

    /**
     * Sets the value of the filler6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller6(String value) {
        this.filler6 = value;
    }

    /**
     * Gets the value of the filler7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller7() {
        return filler7;
    }

    /**
     * Sets the value of the filler7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller7(String value) {
        this.filler7 = value;
    }

    /**
     * Gets the value of the filler8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller8() {
        return filler8;
    }

    /**
     * Sets the value of the filler8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller8(String value) {
        this.filler8 = value;
    }

}
