//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 12:56:42 PM IST 
//


package com.hdfcbank.xsd.otpval.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UidDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UidDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UID_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UID_TOKEN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProofofIdentity" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}ProofofIdentityType" minOccurs="0"/&gt;
 *         &lt;element name="ProofofAddress" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}ProofofAddressType" minOccurs="0"/&gt;
 *         &lt;element name="LanguageProofofAddress" type="{http://uidaiekyc.otpval.xsd.hdfcbank.com}LanguageProofofAddressType" minOccurs="0"/&gt;
 *         &lt;element name="Pht" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Prn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UidDataType", propOrder = {
    "uidno",
    "uidtoken",
    "proofofIdentity",
    "proofofAddress",
    "languageProofofAddress",
    "pht",
    "prn"
})
public class UidDataType {

    @XmlElement(name = "UID_NO")
    protected String uidno;
    @XmlElement(name = "UID_TOKEN")
    protected String uidtoken;
    @XmlElement(name = "ProofofIdentity")
    protected ProofofIdentityType proofofIdentity;
    @XmlElement(name = "ProofofAddress")
    protected ProofofAddressType proofofAddress;
    @XmlElement(name = "LanguageProofofAddress")
    protected LanguageProofofAddressType languageProofofAddress;
    @XmlElement(name = "Pht")
    protected String pht;
    @XmlElement(name = "Prn")
    protected String prn;

    /**
     * Gets the value of the uidno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIDNO() {
        return uidno;
    }

    /**
     * Sets the value of the uidno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIDNO(String value) {
        this.uidno = value;
    }

    /**
     * Gets the value of the uidtoken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIDTOKEN() {
        return uidtoken;
    }

    /**
     * Sets the value of the uidtoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIDTOKEN(String value) {
        this.uidtoken = value;
    }

    /**
     * Gets the value of the proofofIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link ProofofIdentityType }
     *     
     */
    public ProofofIdentityType getProofofIdentity() {
        return proofofIdentity;
    }

    /**
     * Sets the value of the proofofIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProofofIdentityType }
     *     
     */
    public void setProofofIdentity(ProofofIdentityType value) {
        this.proofofIdentity = value;
    }

    /**
     * Gets the value of the proofofAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ProofofAddressType }
     *     
     */
    public ProofofAddressType getProofofAddress() {
        return proofofAddress;
    }

    /**
     * Sets the value of the proofofAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProofofAddressType }
     *     
     */
    public void setProofofAddress(ProofofAddressType value) {
        this.proofofAddress = value;
    }

    /**
     * Gets the value of the languageProofofAddress property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageProofofAddressType }
     *     
     */
    public LanguageProofofAddressType getLanguageProofofAddress() {
        return languageProofofAddress;
    }

    /**
     * Sets the value of the languageProofofAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageProofofAddressType }
     *     
     */
    public void setLanguageProofofAddress(LanguageProofofAddressType value) {
        this.languageProofofAddress = value;
    }

    /**
     * Gets the value of the pht property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPht() {
        return pht;
    }

    /**
     * Sets the value of the pht property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPht(String value) {
        this.pht = value;
    }

    /**
     * Gets the value of the prn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrn() {
        return prn;
    }

    /**
     * Sets the value of the prn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrn(String value) {
        this.prn = value;
    }

}
