//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.25 at 01:34:11 PM IST 
//


package com.hdfcbank.xsd.otp.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eKYCOTPGenrateRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eKYCOTPGenrateRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UID_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OTP" type="{http://uidaiekyc.otp.xsd.hdfcbank.com}otpType" minOccurs="0"/&gt;
 *         &lt;element name="Req_Date_Time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Req_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Cost_Center_No" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionInfo" type="{http://uidaiekyc.otp.xsd.hdfcbank.com}TransactionInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Cert_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Value1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Value2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOAStandardElements" type="{http://uidaiekyc.otp.xsd.hdfcbank.com}soastandarddtls" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eKYCOTPGenrateRequestType", propOrder = {
    "uidno",
    "otp",
    "reqDateTime",
    "reqNo",
    "costCenterNo",
    "transactionInfo",
    "certName",
    "value1",
    "value2",
    "filler1",
    "filler2",
    "filler3",
    "filler4",
    "filler5",
    "soaStandardElements"
})
public class EKYCOTPGenrateRequestType {

    @XmlElement(name = "UID_NO", required = true)
    protected String uidno;
    @XmlElement(name = "OTP")
    protected OtpType otp;
    @XmlElement(name = "Req_Date_Time")
    protected String reqDateTime;
    @XmlElement(name = "Req_No")
    protected String reqNo;
    @XmlElement(name = "Cost_Center_No")
    protected String costCenterNo;
    @XmlElement(name = "TransactionInfo")
    protected TransactionInfoType transactionInfo;
    @XmlElement(name = "Cert_Name")
    protected String certName;
    @XmlElement(name = "Value1")
    protected String value1;
    @XmlElement(name = "Value2")
    protected String value2;
    @XmlElement(name = "Filler1")
    protected String filler1;
    @XmlElement(name = "Filler2")
    protected String filler2;
    @XmlElement(name = "Filler3")
    protected String filler3;
    @XmlElement(name = "Filler4")
    protected String filler4;
    @XmlElement(name = "Filler5")
    protected String filler5;
    @XmlElement(name = "SOAStandardElements")
    protected Soastandarddtls soaStandardElements;

    /**
     * Gets the value of the uidno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIDNO() {
        return uidno;
    }

    /**
     * Sets the value of the uidno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIDNO(String value) {
        this.uidno = value;
    }

    /**
     * Gets the value of the otp property.
     * 
     * @return
     *     possible object is
     *     {@link OtpType }
     *     
     */
    public OtpType getOTP() {
        return otp;
    }

    /**
     * Sets the value of the otp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtpType }
     *     
     */
    public void setOTP(OtpType value) {
        this.otp = value;
    }

    /**
     * Gets the value of the reqDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqDateTime() {
        return reqDateTime;
    }

    /**
     * Sets the value of the reqDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqDateTime(String value) {
        this.reqDateTime = value;
    }

    /**
     * Gets the value of the reqNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqNo() {
        return reqNo;
    }

    /**
     * Sets the value of the reqNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqNo(String value) {
        this.reqNo = value;
    }

    /**
     * Gets the value of the costCenterNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterNo() {
        return costCenterNo;
    }

    /**
     * Sets the value of the costCenterNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterNo(String value) {
        this.costCenterNo = value;
    }

    /**
     * Gets the value of the transactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionInfoType }
     *     
     */
    public TransactionInfoType getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * Sets the value of the transactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionInfoType }
     *     
     */
    public void setTransactionInfo(TransactionInfoType value) {
        this.transactionInfo = value;
    }

    /**
     * Gets the value of the certName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertName() {
        return certName;
    }

    /**
     * Sets the value of the certName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertName(String value) {
        this.certName = value;
    }

    /**
     * Gets the value of the value1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue1() {
        return value1;
    }

    /**
     * Sets the value of the value1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue1(String value) {
        this.value1 = value;
    }

    /**
     * Gets the value of the value2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue2() {
        return value2;
    }

    /**
     * Sets the value of the value2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue2(String value) {
        this.value2 = value;
    }

    /**
     * Gets the value of the filler1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller1() {
        return filler1;
    }

    /**
     * Sets the value of the filler1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller1(String value) {
        this.filler1 = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller2(String value) {
        this.filler2 = value;
    }

    /**
     * Gets the value of the filler3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * Sets the value of the filler3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller3(String value) {
        this.filler3 = value;
    }

    /**
     * Gets the value of the filler4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller4() {
        return filler4;
    }

    /**
     * Sets the value of the filler4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller4(String value) {
        this.filler4 = value;
    }

    /**
     * Gets the value of the filler5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller5() {
        return filler5;
    }

    /**
     * Sets the value of the filler5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller5(String value) {
        this.filler5 = value;
    }

    /**
     * Gets the value of the soaStandardElements property.
     * 
     * @return
     *     possible object is
     *     {@link Soastandarddtls }
     *     
     */
    public Soastandarddtls getSOAStandardElements() {
        return soaStandardElements;
    }

    /**
     * Sets the value of the soaStandardElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Soastandarddtls }
     *     
     */
    public void setSOAStandardElements(Soastandarddtls value) {
        this.soaStandardElements = value;
    }

}
