//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.30 at 09:13:50 AM IST 
//


package com.enstagesas.enstageotpservice.hdfc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enstagesas.enstageotpservice.hdfc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enstagesas.enstageotpservice.hdfc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeneratePwdRequest }
     * 
     */
    public GeneratePwdRequest createGeneratePwdRequest() {
        return new GeneratePwdRequest();
    }

    /**
     * Create an instance of {@link VerifyPwdRequest }
     * 
     */
    public VerifyPwdRequest createVerifyPwdRequest() {
        return new VerifyPwdRequest();
    }

    /**
     * Create an instance of {@link GeneratePwdRequest.HDFCGenPwdReq }
     * 
     */
    public GeneratePwdRequest.HDFCGenPwdReq createGeneratePwdRequestHDFCGenPwdReq() {
        return new GeneratePwdRequest.HDFCGenPwdReq();
    }

    /**
     * Create an instance of {@link VerifyPwdRequest.HDFCVerifyPwdReq }
     * 
     */
    public VerifyPwdRequest.HDFCVerifyPwdReq createVerifyPwdRequestHDFCVerifyPwdReq() {
        return new VerifyPwdRequest.HDFCVerifyPwdReq();
    }

    /**
     * Create an instance of {@link GeneratePwdRequestResponse }
     * 
     */
    public GeneratePwdRequestResponse createGeneratePwdRequestResponse() {
        return new GeneratePwdRequestResponse();
    }

    /**
     * Create an instance of {@link HDFCGenPwdRes }
     * 
     */
    public HDFCGenPwdRes createHDFCGenPwdRes() {
        return new HDFCGenPwdRes();
    }

    /**
     * Create an instance of {@link VerifyPwdRequestReturn }
     * 
     */
    public VerifyPwdRequestReturn createVerifyPwdRequestReturn() {
        return new VerifyPwdRequestReturn();
    }

    /**
     * Create an instance of {@link HDFCVerifyPwdRes }
     * 
     */
    public HDFCVerifyPwdRes createHDFCVerifyPwdRes() {
        return new HDFCVerifyPwdRes();
    }

}
