//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 10:51:23 AM IST 
//


package hdfcbank.ws.otpverification;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hdfcbank.ws.otpverification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VerifyOneTimePasswordRequestArg0BankCode_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "bankCode");
    private final static QName _VerifyOneTimePasswordRequestArg0Channel_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "channel");
    private final static QName _VerifyOneTimePasswordRequestArg0ServiceCode_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "serviceCode");
    private final static QName _VerifyOneTimePasswordRequestArg0UserReferenceNumber_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "userReferenceNumber");
    private final static QName _VerifyOneTimePasswordRequestArg0TransactingPartyCode_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "transactingPartyCode");
    private final static QName _VerifyOneTimePasswordRequestArg0TransactionBranch_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "transactionBranch");
    private final static QName _VerifyOneTimePasswordRequestArg0UserId_QNAME = new QName("http://hdfcbank/ws/OTPVerification", "userId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hdfcbank.ws.otpverification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VerifyOneTimePasswordRequest }
     * 
     */
    public VerifyOneTimePasswordRequest createVerifyOneTimePasswordRequest() {
        return new VerifyOneTimePasswordRequest();
    }

    /**
     * Create an instance of {@link VerifyOneTimePasswordRequest.Arg0 }
     * 
     */
    public VerifyOneTimePasswordRequest.Arg0 createVerifyOneTimePasswordRequestArg0() {
        return new VerifyOneTimePasswordRequest.Arg0();
    }

    /**
     * Create an instance of {@link VerifyOneTimePasswordRequest.Arg1 }
     * 
     */
    public VerifyOneTimePasswordRequest.Arg1 createVerifyOneTimePasswordRequestArg1() {
        return new VerifyOneTimePasswordRequest.Arg1();
    }

    /**
     * Create an instance of {@link VerifyOneTimePasswordResponse }
     * 
     */
    public VerifyOneTimePasswordResponse createVerifyOneTimePasswordResponse() {
        return new VerifyOneTimePasswordResponse();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "bankCode", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0BankCode(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0BankCode_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "channel", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0Channel(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0Channel_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "serviceCode", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0ServiceCode(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0ServiceCode_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "userReferenceNumber", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0UserReferenceNumber(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0UserReferenceNumber_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "transactingPartyCode", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0TransactingPartyCode(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0TransactingPartyCode_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "transactionBranch", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0TransactionBranch(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0TransactionBranch_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://hdfcbank/ws/OTPVerification", name = "userId", scope = VerifyOneTimePasswordRequest.Arg0 .class)
    public JAXBElement<String> createVerifyOneTimePasswordRequestArg0UserId(String value) {
        return new JAXBElement<String>(_VerifyOneTimePasswordRequestArg0UserId_QNAME, String.class, VerifyOneTimePasswordRequest.Arg0 .class, value);
    }

}
