//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 10:51:23 AM IST 
//


package hdfcbank.ws.otpverification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for return complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="return"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status" type="{http://hdfcbank/ws/OTPVerification}status"/&gt;
 *         &lt;element name="fillerField1" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="fillerField2" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="fillerField3" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="fillerField4" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="fillerField5" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "return", propOrder = {
    "status",
    "fillerField1",
    "fillerField2",
    "fillerField3",
    "fillerField4",
    "fillerField5"
})
public class Return {

    @XmlElement(required = true)
    protected Status status;
    @XmlElement(required = true)
    protected Object fillerField1;
    @XmlElement(required = true)
    protected Object fillerField2;
    @XmlElement(required = true)
    protected Object fillerField3;
    @XmlElement(required = true)
    protected Object fillerField4;
    @XmlElement(required = true)
    protected Object fillerField5;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the fillerField1 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFillerField1() {
        return fillerField1;
    }

    /**
     * Sets the value of the fillerField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFillerField1(Object value) {
        this.fillerField1 = value;
    }

    /**
     * Gets the value of the fillerField2 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFillerField2() {
        return fillerField2;
    }

    /**
     * Sets the value of the fillerField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFillerField2(Object value) {
        this.fillerField2 = value;
    }

    /**
     * Gets the value of the fillerField3 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFillerField3() {
        return fillerField3;
    }

    /**
     * Sets the value of the fillerField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFillerField3(Object value) {
        this.fillerField3 = value;
    }

    /**
     * Gets the value of the fillerField4 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFillerField4() {
        return fillerField4;
    }

    /**
     * Sets the value of the fillerField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFillerField4(Object value) {
        this.fillerField4 = value;
    }

    /**
     * Gets the value of the fillerField5 property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFillerField5() {
        return fillerField5;
    }

    /**
     * Sets the value of the fillerField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFillerField5(Object value) {
        this.fillerField5 = value;
    }

}
