//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 10:51:23 AM IST 
//


package hdfcbank.ws.otpverification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for status complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="status"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="extendedReply" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="externalReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="internalReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isOverriden" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="postingDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="replyCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="replyText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "status", propOrder = {
    "errorCode",
    "extendedReply",
    "externalReferenceNo",
    "internalReferenceNumber",
    "isOverriden",
    "postingDate",
    "replyCode",
    "replyText",
    "userReferenceNumber"
})
public class Status {

    @XmlElement(required = true)
    protected String errorCode;
    @XmlElement(required = true)
    protected String extendedReply;
    @XmlElement(required = true)
    protected String externalReferenceNo;
    @XmlElement(required = true)
    protected String internalReferenceNumber;
    @XmlElement(required = true)
    protected String isOverriden;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar postingDate;
    protected int replyCode;
    @XmlElement(required = true)
    protected String replyText;
    @XmlElement(required = true)
    protected String userReferenceNumber;

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the extendedReply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedReply() {
        return extendedReply;
    }

    /**
     * Sets the value of the extendedReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedReply(String value) {
        this.extendedReply = value;
    }

    /**
     * Gets the value of the externalReferenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReferenceNo() {
        return externalReferenceNo;
    }

    /**
     * Sets the value of the externalReferenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReferenceNo(String value) {
        this.externalReferenceNo = value;
    }

    /**
     * Gets the value of the internalReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalReferenceNumber() {
        return internalReferenceNumber;
    }

    /**
     * Sets the value of the internalReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalReferenceNumber(String value) {
        this.internalReferenceNumber = value;
    }

    /**
     * Gets the value of the isOverriden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOverriden() {
        return isOverriden;
    }

    /**
     * Sets the value of the isOverriden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOverriden(String value) {
        this.isOverriden = value;
    }

    /**
     * Gets the value of the postingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostingDate() {
        return postingDate;
    }

    /**
     * Sets the value of the postingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostingDate(XMLGregorianCalendar value) {
        this.postingDate = value;
    }

    /**
     * Gets the value of the replyCode property.
     * 
     */
    public int getReplyCode() {
        return replyCode;
    }

    /**
     * Sets the value of the replyCode property.
     * 
     */
    public void setReplyCode(int value) {
        this.replyCode = value;
    }

    /**
     * Gets the value of the replyText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyText() {
        return replyText;
    }

    /**
     * Sets the value of the replyText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyText(String value) {
        this.replyText = value;
    }

    /**
     * Gets the value of the userReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReferenceNumber() {
        return userReferenceNumber;
    }

    /**
     * Sets the value of the userReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReferenceNumber(String value) {
        this.userReferenceNumber = value;
    }

}
