//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.14 at 12:07:52 PM IST 
//


package com.hdfcbank.otpservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="generatePwdRequestReturn" type="{http://www.hdfcbank.com/OTPService/}generatePwdRequestReturn"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generatePwdRequestReturn"
})
@XmlRootElement(name = "generatePwdRequestResponse")
public class GeneratePwdRequestResponse {

    @XmlElement(required = true)
    protected GeneratePwdRequestReturn generatePwdRequestReturn;

    /**
     * Gets the value of the generatePwdRequestReturn property.
     * 
     * @return
     *     possible object is
     *     {@link GeneratePwdRequestReturn }
     *     
     */
    public GeneratePwdRequestReturn getGeneratePwdRequestReturn() {
        return generatePwdRequestReturn;
    }

    /**
     * Sets the value of the generatePwdRequestReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneratePwdRequestReturn }
     *     
     */
    public void setGeneratePwdRequestReturn(GeneratePwdRequestReturn value) {
        this.generatePwdRequestReturn = value;
    }

}
