//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.14 at 12:07:52 PM IST 
//


package com.hdfcbank.otpservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for generatePwdRequestReturn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="generatePwdRequestReturn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HDFCGenPwdRes" type="{http://www.hdfcbank.com/OTPService/}HDFCGenPwdRes"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generatePwdRequestReturn", propOrder = {
    "hdfcGenPwdRes"
})
public class GeneratePwdRequestReturn {

    @XmlElement(name = "HDFCGenPwdRes", required = true)
    protected HDFCGenPwdRes hdfcGenPwdRes;

    /**
     * Gets the value of the hdfcGenPwdRes property.
     * 
     * @return
     *     possible object is
     *     {@link HDFCGenPwdRes }
     *     
     */
    public HDFCGenPwdRes getHDFCGenPwdRes() {
        return hdfcGenPwdRes;
    }

    /**
     * Sets the value of the hdfcGenPwdRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HDFCGenPwdRes }
     *     
     */
    public void setHDFCGenPwdRes(HDFCGenPwdRes value) {
        this.hdfcGenPwdRes = value;
    }

}
