//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package hdfcbank.ws.dedupecheck;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClosedAccSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClosedAccSummaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClosedAccMatch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ClosedAcc" type="{http://hdfcbank/ws/DedupeCheck}MatchValueType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClosedAccSummaryType", propOrder = {
    "closedAccMatch",
    "closedAcc"
})
public class ClosedAccSummaryType {

    @XmlElement(name = "ClosedAccMatch", required = true)
    protected String closedAccMatch;
    @XmlElement(name = "ClosedAcc", required = true)
    protected MatchValueType closedAcc;

    /**
     * Gets the value of the closedAccMatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosedAccMatch() {
        return closedAccMatch;
    }

    /**
     * Sets the value of the closedAccMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedAccMatch(String value) {
        this.closedAccMatch = value;
    }

    /**
     * Gets the value of the closedAcc property.
     * 
     * @return
     *     possible object is
     *     {@link MatchValueType }
     *     
     */
    public MatchValueType getClosedAcc() {
        return closedAcc;
    }

    /**
     * Sets the value of the closedAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchValueType }
     *     
     */
    public void setClosedAcc(MatchValueType value) {
        this.closedAcc = value;
    }

}
