//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package hdfcbank.ws.dedupecheck;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DedupeResponseHeaderInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DedupeResponseHeaderInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SourceSystemName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RequestNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AODNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RequestorUserID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EnquiryDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EnquiryBranch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MatchProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MACAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOACommonResponse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FactivaResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ClosedAccountResponseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DedupeResponseHeaderInfoType", propOrder = {
    "sourceSystemName",
    "requestNumber",
    "aodNumber",
    "customerCategory",
    "requestorUserID",
    "enquiryDateTime",
    "enquiryBranch",
    "matchProfile",
    "ipAddress",
    "macAddress",
    "soaCommonResponse",
    "factivaResponseCode",
    "closedAccountResponseCode"
})
public class DedupeResponseHeaderInfoType {

    @XmlElement(name = "SourceSystemName", required = true)
    protected String sourceSystemName;
    @XmlElement(name = "RequestNumber", required = true)
    protected String requestNumber;
    @XmlElement(name = "AODNumber")
    protected String aodNumber;
    @XmlElement(name = "CustomerCategory")
    protected String customerCategory;
    @XmlElement(name = "RequestorUserID", required = true)
    protected String requestorUserID;
    @XmlElement(name = "EnquiryDateTime", required = true)
    protected String enquiryDateTime;
    @XmlElement(name = "EnquiryBranch", required = true)
    protected String enquiryBranch;
    @XmlElement(name = "MatchProfile")
    protected String matchProfile;
    @XmlElement(name = "IPAddress")
    protected String ipAddress;
    @XmlElement(name = "MACAddress")
    protected String macAddress;
    @XmlElement(name = "SOACommonResponse")
    protected String soaCommonResponse;
    @XmlElement(name = "FactivaResponseCode")
    protected String factivaResponseCode;
    @XmlElement(name = "ClosedAccountResponseCode")
    protected String closedAccountResponseCode;

    /**
     * Gets the value of the sourceSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemName() {
        return sourceSystemName;
    }

    /**
     * Sets the value of the sourceSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemName(String value) {
        this.sourceSystemName = value;
    }

    /**
     * Gets the value of the requestNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestNumber() {
        return requestNumber;
    }

    /**
     * Sets the value of the requestNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestNumber(String value) {
        this.requestNumber = value;
    }

    /**
     * Gets the value of the aodNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAODNumber() {
        return aodNumber;
    }

    /**
     * Sets the value of the aodNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAODNumber(String value) {
        this.aodNumber = value;
    }

    /**
     * Gets the value of the customerCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCategory() {
        return customerCategory;
    }

    /**
     * Sets the value of the customerCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCategory(String value) {
        this.customerCategory = value;
    }

    /**
     * Gets the value of the requestorUserID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorUserID() {
        return requestorUserID;
    }

    /**
     * Sets the value of the requestorUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorUserID(String value) {
        this.requestorUserID = value;
    }

    /**
     * Gets the value of the enquiryDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryDateTime() {
        return enquiryDateTime;
    }

    /**
     * Sets the value of the enquiryDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryDateTime(String value) {
        this.enquiryDateTime = value;
    }

    /**
     * Gets the value of the enquiryBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryBranch() {
        return enquiryBranch;
    }

    /**
     * Sets the value of the enquiryBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryBranch(String value) {
        this.enquiryBranch = value;
    }

    /**
     * Gets the value of the matchProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchProfile() {
        return matchProfile;
    }

    /**
     * Sets the value of the matchProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchProfile(String value) {
        this.matchProfile = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the macAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMACAddress() {
        return macAddress;
    }

    /**
     * Sets the value of the macAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMACAddress(String value) {
        this.macAddress = value;
    }

    /**
     * Gets the value of the soaCommonResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOACommonResponse() {
        return soaCommonResponse;
    }

    /**
     * Sets the value of the soaCommonResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOACommonResponse(String value) {
        this.soaCommonResponse = value;
    }

    /**
     * Gets the value of the factivaResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactivaResponseCode() {
        return factivaResponseCode;
    }

    /**
     * Sets the value of the factivaResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactivaResponseCode(String value) {
        this.factivaResponseCode = value;
    }

    /**
     * Gets the value of the closedAccountResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosedAccountResponseCode() {
        return closedAccountResponseCode;
    }

    /**
     * Sets the value of the closedAccountResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedAccountResponseCode(String value) {
        this.closedAccountResponseCode = value;
    }

}
