//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package hdfcbank.ws.dedupecheck;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HeaderInfo" type="{http://hdfcbank/ws/DedupeCheck}DedupeResponseHeaderInfoType"/&gt;
 *         &lt;element name="EnquiryInfo" type="{http://hdfcbank/ws/DedupeCheck}DedupeResponseEnquiryInfoType"/&gt;
 *         &lt;element name="Summary" type="{http://hdfcbank/ws/DedupeCheck}SummaryType"/&gt;
 *         &lt;element name="Detail" type="{http://hdfcbank/ws/DedupeCheck}DetailType"/&gt;
 *         &lt;element name="NegativeList" type="{http://hdfcbank/ws/DedupeCheck}NegativeListType"/&gt;
 *         &lt;element name="ClosedAccSummary" type="{http://hdfcbank/ws/DedupeCheck}ClosedAccSummaryType"/&gt;
 *         &lt;element name="ClosedAccMatch" type="{http://hdfcbank/ws/DedupeCheck}ClosedAccMatchType"/&gt;
 *         &lt;element name="ClosedAccDetail" type="{http://hdfcbank/ws/DedupeCheck}ClosedAccDetailType"/&gt;
 *         &lt;element name="soaFillers" type="{http://hdfcbank/ws/DedupeCheck}soaFillers"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerInfo",
    "enquiryInfo",
    "summary",
    "detail",
    "negativeList",
    "closedAccSummary",
    "closedAccMatch",
    "closedAccDetail",
    "soaFillers"
})
@XmlRootElement(name = "DedupeServiceResponse")
public class DedupeServiceResponse {

    @XmlElement(name = "HeaderInfo", required = true)
    protected DedupeResponseHeaderInfoType headerInfo;
    @XmlElement(name = "EnquiryInfo", required = true)
    protected DedupeResponseEnquiryInfoType enquiryInfo;
    @XmlElement(name = "Summary", required = true)
    protected SummaryType summary;
    @XmlElement(name = "Detail", required = true)
    protected DetailType detail;
    @XmlElement(name = "NegativeList", required = true)
    protected NegativeListType negativeList;
    @XmlElement(name = "ClosedAccSummary", required = true)
    protected ClosedAccSummaryType closedAccSummary;
    @XmlElement(name = "ClosedAccMatch", required = true)
    protected ClosedAccMatchType closedAccMatch;
    @XmlElement(name = "ClosedAccDetail", required = true)
    protected ClosedAccDetailType closedAccDetail;
    @XmlElement(required = true)
    protected SoaFillers soaFillers;

    /**
     * Gets the value of the headerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DedupeResponseHeaderInfoType }
     *     
     */
    public DedupeResponseHeaderInfoType getHeaderInfo() {
        return headerInfo;
    }

    /**
     * Sets the value of the headerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DedupeResponseHeaderInfoType }
     *     
     */
    public void setHeaderInfo(DedupeResponseHeaderInfoType value) {
        this.headerInfo = value;
    }

    /**
     * Gets the value of the enquiryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DedupeResponseEnquiryInfoType }
     *     
     */
    public DedupeResponseEnquiryInfoType getEnquiryInfo() {
        return enquiryInfo;
    }

    /**
     * Sets the value of the enquiryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DedupeResponseEnquiryInfoType }
     *     
     */
    public void setEnquiryInfo(DedupeResponseEnquiryInfoType value) {
        this.enquiryInfo = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryType }
     *     
     */
    public SummaryType getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryType }
     *     
     */
    public void setSummary(SummaryType value) {
        this.summary = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link DetailType }
     *     
     */
    public DetailType getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailType }
     *     
     */
    public void setDetail(DetailType value) {
        this.detail = value;
    }

    /**
     * Gets the value of the negativeList property.
     * 
     * @return
     *     possible object is
     *     {@link NegativeListType }
     *     
     */
    public NegativeListType getNegativeList() {
        return negativeList;
    }

    /**
     * Sets the value of the negativeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegativeListType }
     *     
     */
    public void setNegativeList(NegativeListType value) {
        this.negativeList = value;
    }

    /**
     * Gets the value of the closedAccSummary property.
     * 
     * @return
     *     possible object is
     *     {@link ClosedAccSummaryType }
     *     
     */
    public ClosedAccSummaryType getClosedAccSummary() {
        return closedAccSummary;
    }

    /**
     * Sets the value of the closedAccSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClosedAccSummaryType }
     *     
     */
    public void setClosedAccSummary(ClosedAccSummaryType value) {
        this.closedAccSummary = value;
    }

    /**
     * Gets the value of the closedAccMatch property.
     * 
     * @return
     *     possible object is
     *     {@link ClosedAccMatchType }
     *     
     */
    public ClosedAccMatchType getClosedAccMatch() {
        return closedAccMatch;
    }

    /**
     * Sets the value of the closedAccMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClosedAccMatchType }
     *     
     */
    public void setClosedAccMatch(ClosedAccMatchType value) {
        this.closedAccMatch = value;
    }

    /**
     * Gets the value of the closedAccDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ClosedAccDetailType }
     *     
     */
    public ClosedAccDetailType getClosedAccDetail() {
        return closedAccDetail;
    }

    /**
     * Sets the value of the closedAccDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClosedAccDetailType }
     *     
     */
    public void setClosedAccDetail(ClosedAccDetailType value) {
        this.closedAccDetail = value;
    }

    /**
     * Gets the value of the soaFillers property.
     * 
     * @return
     *     possible object is
     *     {@link SoaFillers }
     *     
     */
    public SoaFillers getSoaFillers() {
        return soaFillers;
    }

    /**
     * Sets the value of the soaFillers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoaFillers }
     *     
     */
    public void setSoaFillers(SoaFillers value) {
        this.soaFillers = value;
    }

}
