//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.27 at 09:57:19 AM IST 
//


package hdfcbank.ws.dedupecheck;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Factiva" type="{http://hdfcbank/ws/DedupeCheck}MatchValueType"/&gt;
 *         &lt;element name="PersonEntityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Deceased" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PersonStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NameType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NameSubType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TitleHonorific" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RoleType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationSinceDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationSinceMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationSinceYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationToDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationToMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OccupationToYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Day" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PlaceOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SanctionList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SLRSinceDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SLRSinceMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SLRSinceYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SLRToDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SLRToMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SLRToYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselCallSign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselTonnage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselGRT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CountryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdentificationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IdentificationNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SourceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProfileNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Image" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RelatedPersonEntityID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Relationship" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsEx" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AdditionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastReviewedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler13" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler14" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Filler15" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetailType", propOrder = {
    "factiva",
    "personEntityId",
    "action",
    "gender",
    "deceased",
    "personStatus",
    "nameType",
    "nameSubType",
    "titleHonorific",
    "firstName",
    "middleName",
    "surname",
    "suffix",
    "description1",
    "description2",
    "description3",
    "roleType",
    "occupationCategory",
    "title",
    "occupationSinceDay",
    "occupationSinceMonth",
    "occupationSinceYear",
    "occupationToDay",
    "occupationToMonth",
    "occupationToYear",
    "dateType",
    "day",
    "month",
    "year",
    "dateNotes",
    "placeOfBirth",
    "sanctionList",
    "slrSinceDay",
    "slrSinceMonth",
    "slrSinceYear",
    "slrToDay",
    "slrToMonth",
    "slrToYear",
    "address",
    "city",
    "country",
    "url",
    "vesselCallSign",
    "vesselType",
    "vesselTonnage",
    "vesselGRT",
    "vesselOwner",
    "vesselFlag",
    "countryType",
    "vesselCountry",
    "identificationType",
    "identificationNumber",
    "identificationNotes",
    "sourceName",
    "profileNotes",
    "image",
    "relatedPersonEntityID",
    "relationship",
    "isEx",
    "additionDate",
    "lastReviewedDate",
    "filler1",
    "filler2",
    "filler3",
    "filler4",
    "filler5",
    "filler6",
    "filler7",
    "filler8",
    "filler9",
    "filler10",
    "filler11",
    "filler12",
    "filler13",
    "filler14",
    "filler15"
})
public class DetailType {

    @XmlElement(name = "Factiva", required = true)
    protected MatchValueType factiva;
    @XmlElement(name = "PersonEntityId")
    protected String personEntityId;
    @XmlElement(name = "Action")
    protected String action;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "Deceased")
    protected String deceased;
    @XmlElement(name = "PersonStatus")
    protected String personStatus;
    @XmlElement(name = "NameType")
    protected String nameType;
    @XmlElement(name = "NameSubType")
    protected String nameSubType;
    @XmlElement(name = "TitleHonorific")
    protected String titleHonorific;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "Surname")
    protected String surname;
    @XmlElement(name = "Suffix")
    protected String suffix;
    @XmlElement(name = "Description1")
    protected String description1;
    @XmlElement(name = "Description2")
    protected String description2;
    @XmlElement(name = "Description3")
    protected String description3;
    @XmlElement(name = "RoleType")
    protected String roleType;
    @XmlElement(name = "OccupationCategory")
    protected String occupationCategory;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "OccupationSinceDay")
    protected String occupationSinceDay;
    @XmlElement(name = "OccupationSinceMonth")
    protected String occupationSinceMonth;
    @XmlElement(name = "OccupationSinceYear")
    protected String occupationSinceYear;
    @XmlElement(name = "OccupationToDay")
    protected String occupationToDay;
    @XmlElement(name = "OccupationToMonth")
    protected String occupationToMonth;
    @XmlElement(name = "OccupationToYear")
    protected String occupationToYear;
    @XmlElement(name = "DateType")
    protected String dateType;
    @XmlElement(name = "Day")
    protected String day;
    @XmlElement(name = "Month")
    protected String month;
    @XmlElement(name = "Year")
    protected String year;
    @XmlElement(name = "DateNotes")
    protected String dateNotes;
    @XmlElement(name = "PlaceOfBirth")
    protected String placeOfBirth;
    @XmlElement(name = "SanctionList")
    protected String sanctionList;
    @XmlElement(name = "SLRSinceDay")
    protected String slrSinceDay;
    @XmlElement(name = "SLRSinceMonth")
    protected String slrSinceMonth;
    @XmlElement(name = "SLRSinceYear")
    protected String slrSinceYear;
    @XmlElement(name = "SLRToDay")
    protected String slrToDay;
    @XmlElement(name = "SLRToMonth")
    protected String slrToMonth;
    @XmlElement(name = "SLRToYear")
    protected String slrToYear;
    @XmlElement(name = "Address")
    protected String address;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "URL")
    protected String url;
    @XmlElement(name = "VesselCallSign")
    protected String vesselCallSign;
    @XmlElement(name = "VesselType")
    protected String vesselType;
    @XmlElement(name = "VesselTonnage")
    protected String vesselTonnage;
    @XmlElement(name = "VesselGRT")
    protected String vesselGRT;
    @XmlElement(name = "VesselOwner")
    protected String vesselOwner;
    @XmlElement(name = "VesselFlag")
    protected String vesselFlag;
    @XmlElement(name = "CountryType")
    protected String countryType;
    @XmlElement(name = "VesselCountry")
    protected String vesselCountry;
    @XmlElement(name = "IdentificationType")
    protected String identificationType;
    @XmlElement(name = "IdentificationNumber")
    protected String identificationNumber;
    @XmlElement(name = "IdentificationNotes")
    protected String identificationNotes;
    @XmlElement(name = "SourceName")
    protected String sourceName;
    @XmlElement(name = "ProfileNotes")
    protected String profileNotes;
    @XmlElement(name = "Image")
    protected String image;
    @XmlElement(name = "RelatedPersonEntityID")
    protected String relatedPersonEntityID;
    @XmlElement(name = "Relationship")
    protected String relationship;
    @XmlElement(name = "IsEx")
    protected String isEx;
    @XmlElement(name = "AdditionDate")
    protected String additionDate;
    @XmlElement(name = "LastReviewedDate")
    protected String lastReviewedDate;
    @XmlElement(name = "Filler1")
    protected String filler1;
    @XmlElement(name = "Filler2")
    protected String filler2;
    @XmlElement(name = "Filler3")
    protected String filler3;
    @XmlElement(name = "Filler4")
    protected String filler4;
    @XmlElement(name = "Filler5")
    protected String filler5;
    @XmlElement(name = "Filler6")
    protected String filler6;
    @XmlElement(name = "Filler7")
    protected String filler7;
    @XmlElement(name = "Filler8")
    protected String filler8;
    @XmlElement(name = "Filler9")
    protected String filler9;
    @XmlElement(name = "Filler10")
    protected String filler10;
    @XmlElement(name = "Filler11")
    protected String filler11;
    @XmlElement(name = "Filler12")
    protected String filler12;
    @XmlElement(name = "Filler13")
    protected String filler13;
    @XmlElement(name = "Filler14")
    protected String filler14;
    @XmlElement(name = "Filler15")
    protected String filler15;

    /**
     * Gets the value of the factiva property.
     * 
     * @return
     *     possible object is
     *     {@link MatchValueType }
     *     
     */
    public MatchValueType getFactiva() {
        return factiva;
    }

    /**
     * Sets the value of the factiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchValueType }
     *     
     */
    public void setFactiva(MatchValueType value) {
        this.factiva = value;
    }

    /**
     * Gets the value of the personEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonEntityId() {
        return personEntityId;
    }

    /**
     * Sets the value of the personEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonEntityId(String value) {
        this.personEntityId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the deceased property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeceased() {
        return deceased;
    }

    /**
     * Sets the value of the deceased property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeceased(String value) {
        this.deceased = value;
    }

    /**
     * Gets the value of the personStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonStatus() {
        return personStatus;
    }

    /**
     * Sets the value of the personStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonStatus(String value) {
        this.personStatus = value;
    }

    /**
     * Gets the value of the nameType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameType() {
        return nameType;
    }

    /**
     * Sets the value of the nameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameType(String value) {
        this.nameType = value;
    }

    /**
     * Gets the value of the nameSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSubType() {
        return nameSubType;
    }

    /**
     * Sets the value of the nameSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSubType(String value) {
        this.nameSubType = value;
    }

    /**
     * Gets the value of the titleHonorific property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleHonorific() {
        return titleHonorific;
    }

    /**
     * Sets the value of the titleHonorific property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleHonorific(String value) {
        this.titleHonorific = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the description1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription1() {
        return description1;
    }

    /**
     * Sets the value of the description1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription1(String value) {
        this.description1 = value;
    }

    /**
     * Gets the value of the description2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * Sets the value of the description2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription2(String value) {
        this.description2 = value;
    }

    /**
     * Gets the value of the description3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription3() {
        return description3;
    }

    /**
     * Sets the value of the description3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription3(String value) {
        this.description3 = value;
    }

    /**
     * Gets the value of the roleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * Sets the value of the roleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleType(String value) {
        this.roleType = value;
    }

    /**
     * Gets the value of the occupationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationCategory() {
        return occupationCategory;
    }

    /**
     * Sets the value of the occupationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationCategory(String value) {
        this.occupationCategory = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the occupationSinceDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationSinceDay() {
        return occupationSinceDay;
    }

    /**
     * Sets the value of the occupationSinceDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationSinceDay(String value) {
        this.occupationSinceDay = value;
    }

    /**
     * Gets the value of the occupationSinceMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationSinceMonth() {
        return occupationSinceMonth;
    }

    /**
     * Sets the value of the occupationSinceMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationSinceMonth(String value) {
        this.occupationSinceMonth = value;
    }

    /**
     * Gets the value of the occupationSinceYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationSinceYear() {
        return occupationSinceYear;
    }

    /**
     * Sets the value of the occupationSinceYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationSinceYear(String value) {
        this.occupationSinceYear = value;
    }

    /**
     * Gets the value of the occupationToDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationToDay() {
        return occupationToDay;
    }

    /**
     * Sets the value of the occupationToDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationToDay(String value) {
        this.occupationToDay = value;
    }

    /**
     * Gets the value of the occupationToMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationToMonth() {
        return occupationToMonth;
    }

    /**
     * Sets the value of the occupationToMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationToMonth(String value) {
        this.occupationToMonth = value;
    }

    /**
     * Gets the value of the occupationToYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationToYear() {
        return occupationToYear;
    }

    /**
     * Sets the value of the occupationToYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationToYear(String value) {
        this.occupationToYear = value;
    }

    /**
     * Gets the value of the dateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * Sets the value of the dateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateType(String value) {
        this.dateType = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay(String value) {
        this.day = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonth(String value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the dateNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateNotes() {
        return dateNotes;
    }

    /**
     * Sets the value of the dateNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateNotes(String value) {
        this.dateNotes = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the sanctionList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSanctionList() {
        return sanctionList;
    }

    /**
     * Sets the value of the sanctionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSanctionList(String value) {
        this.sanctionList = value;
    }

    /**
     * Gets the value of the slrSinceDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLRSinceDay() {
        return slrSinceDay;
    }

    /**
     * Sets the value of the slrSinceDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLRSinceDay(String value) {
        this.slrSinceDay = value;
    }

    /**
     * Gets the value of the slrSinceMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLRSinceMonth() {
        return slrSinceMonth;
    }

    /**
     * Sets the value of the slrSinceMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLRSinceMonth(String value) {
        this.slrSinceMonth = value;
    }

    /**
     * Gets the value of the slrSinceYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLRSinceYear() {
        return slrSinceYear;
    }

    /**
     * Sets the value of the slrSinceYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLRSinceYear(String value) {
        this.slrSinceYear = value;
    }

    /**
     * Gets the value of the slrToDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLRToDay() {
        return slrToDay;
    }

    /**
     * Sets the value of the slrToDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLRToDay(String value) {
        this.slrToDay = value;
    }

    /**
     * Gets the value of the slrToMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLRToMonth() {
        return slrToMonth;
    }

    /**
     * Sets the value of the slrToMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLRToMonth(String value) {
        this.slrToMonth = value;
    }

    /**
     * Gets the value of the slrToYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLRToYear() {
        return slrToYear;
    }

    /**
     * Sets the value of the slrToYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLRToYear(String value) {
        this.slrToYear = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the vesselCallSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselCallSign() {
        return vesselCallSign;
    }

    /**
     * Sets the value of the vesselCallSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselCallSign(String value) {
        this.vesselCallSign = value;
    }

    /**
     * Gets the value of the vesselType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselType() {
        return vesselType;
    }

    /**
     * Sets the value of the vesselType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselType(String value) {
        this.vesselType = value;
    }

    /**
     * Gets the value of the vesselTonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselTonnage() {
        return vesselTonnage;
    }

    /**
     * Sets the value of the vesselTonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselTonnage(String value) {
        this.vesselTonnage = value;
    }

    /**
     * Gets the value of the vesselGRT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselGRT() {
        return vesselGRT;
    }

    /**
     * Sets the value of the vesselGRT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselGRT(String value) {
        this.vesselGRT = value;
    }

    /**
     * Gets the value of the vesselOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselOwner() {
        return vesselOwner;
    }

    /**
     * Sets the value of the vesselOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselOwner(String value) {
        this.vesselOwner = value;
    }

    /**
     * Gets the value of the vesselFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselFlag() {
        return vesselFlag;
    }

    /**
     * Sets the value of the vesselFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselFlag(String value) {
        this.vesselFlag = value;
    }

    /**
     * Gets the value of the countryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryType() {
        return countryType;
    }

    /**
     * Sets the value of the countryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryType(String value) {
        this.countryType = value;
    }

    /**
     * Gets the value of the vesselCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselCountry() {
        return vesselCountry;
    }

    /**
     * Sets the value of the vesselCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselCountry(String value) {
        this.vesselCountry = value;
    }

    /**
     * Gets the value of the identificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationType() {
        return identificationType;
    }

    /**
     * Sets the value of the identificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationType(String value) {
        this.identificationType = value;
    }

    /**
     * Gets the value of the identificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationNumber() {
        return identificationNumber;
    }

    /**
     * Sets the value of the identificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationNumber(String value) {
        this.identificationNumber = value;
    }

    /**
     * Gets the value of the identificationNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationNotes() {
        return identificationNotes;
    }

    /**
     * Sets the value of the identificationNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationNotes(String value) {
        this.identificationNotes = value;
    }

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceName(String value) {
        this.sourceName = value;
    }

    /**
     * Gets the value of the profileNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileNotes() {
        return profileNotes;
    }

    /**
     * Sets the value of the profileNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileNotes(String value) {
        this.profileNotes = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the relatedPersonEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedPersonEntityID() {
        return relatedPersonEntityID;
    }

    /**
     * Sets the value of the relatedPersonEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedPersonEntityID(String value) {
        this.relatedPersonEntityID = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationship(String value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the isEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEx() {
        return isEx;
    }

    /**
     * Sets the value of the isEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEx(String value) {
        this.isEx = value;
    }

    /**
     * Gets the value of the additionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionDate() {
        return additionDate;
    }

    /**
     * Sets the value of the additionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionDate(String value) {
        this.additionDate = value;
    }

    /**
     * Gets the value of the lastReviewedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastReviewedDate() {
        return lastReviewedDate;
    }

    /**
     * Sets the value of the lastReviewedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastReviewedDate(String value) {
        this.lastReviewedDate = value;
    }

    /**
     * Gets the value of the filler1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller1() {
        return filler1;
    }

    /**
     * Sets the value of the filler1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller1(String value) {
        this.filler1 = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller2(String value) {
        this.filler2 = value;
    }

    /**
     * Gets the value of the filler3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * Sets the value of the filler3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller3(String value) {
        this.filler3 = value;
    }

    /**
     * Gets the value of the filler4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller4() {
        return filler4;
    }

    /**
     * Sets the value of the filler4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller4(String value) {
        this.filler4 = value;
    }

    /**
     * Gets the value of the filler5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller5() {
        return filler5;
    }

    /**
     * Sets the value of the filler5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller5(String value) {
        this.filler5 = value;
    }

    /**
     * Gets the value of the filler6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller6() {
        return filler6;
    }

    /**
     * Sets the value of the filler6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller6(String value) {
        this.filler6 = value;
    }

    /**
     * Gets the value of the filler7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller7() {
        return filler7;
    }

    /**
     * Sets the value of the filler7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller7(String value) {
        this.filler7 = value;
    }

    /**
     * Gets the value of the filler8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller8() {
        return filler8;
    }

    /**
     * Sets the value of the filler8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller8(String value) {
        this.filler8 = value;
    }

    /**
     * Gets the value of the filler9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller9() {
        return filler9;
    }

    /**
     * Sets the value of the filler9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller9(String value) {
        this.filler9 = value;
    }

    /**
     * Gets the value of the filler10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller10() {
        return filler10;
    }

    /**
     * Sets the value of the filler10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller10(String value) {
        this.filler10 = value;
    }

    /**
     * Gets the value of the filler11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller11() {
        return filler11;
    }

    /**
     * Sets the value of the filler11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller11(String value) {
        this.filler11 = value;
    }

    /**
     * Gets the value of the filler12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller12() {
        return filler12;
    }

    /**
     * Sets the value of the filler12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller12(String value) {
        this.filler12 = value;
    }

    /**
     * Gets the value of the filler13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller13() {
        return filler13;
    }

    /**
     * Sets the value of the filler13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller13(String value) {
        this.filler13 = value;
    }

    /**
     * Gets the value of the filler14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller14() {
        return filler14;
    }

    /**
     * Sets the value of the filler14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller14(String value) {
        this.filler14 = value;
    }

    /**
     * Gets the value of the filler15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller15() {
        return filler15;
    }

    /**
     * Sets the value of the filler15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller15(String value) {
        this.filler15 = value;
    }

}
