//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.27 at 09:57:19 AM IST 
//


package hdfcbank.ws.dedupecheck;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SourceSystem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RequestNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MatchProfile" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FactivaType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ClosedAccountType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SOACommonResponse" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="soaFillers" type="{http://hdfcbank/ws/DedupeCheck}soaFillers" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceSystem",
    "requestNumber",
    "matchProfile",
    "type",
    "factivaType",
    "closedAccountType",
    "soaCommonResponse",
    "soaFillers"
})
@XmlRootElement(name = "getStatusServiceResponse")
public class GetStatusServiceResponse {

    @XmlElement(name = "SourceSystem", required = true)
    protected String sourceSystem;
    @XmlElement(name = "RequestNumber", required = true)
    protected String requestNumber;
    @XmlElement(name = "MatchProfile", required = true)
    protected String matchProfile;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "FactivaType", required = true)
    protected String factivaType;
    @XmlElement(name = "ClosedAccountType", required = true)
    protected String closedAccountType;
    @XmlElement(name = "SOACommonResponse", required = true)
    protected String soaCommonResponse;
    protected SoaFillers soaFillers;

    /**
     * Gets the value of the sourceSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * Sets the value of the sourceSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystem(String value) {
        this.sourceSystem = value;
    }

    /**
     * Gets the value of the requestNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestNumber() {
        return requestNumber;
    }

    /**
     * Sets the value of the requestNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestNumber(String value) {
        this.requestNumber = value;
    }

    /**
     * Gets the value of the matchProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchProfile() {
        return matchProfile;
    }

    /**
     * Sets the value of the matchProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchProfile(String value) {
        this.matchProfile = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the factivaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactivaType() {
        return factivaType;
    }

    /**
     * Sets the value of the factivaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactivaType(String value) {
        this.factivaType = value;
    }

    /**
     * Gets the value of the closedAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosedAccountType() {
        return closedAccountType;
    }

    /**
     * Sets the value of the closedAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedAccountType(String value) {
        this.closedAccountType = value;
    }

    /**
     * Gets the value of the soaCommonResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOACommonResponse() {
        return soaCommonResponse;
    }

    /**
     * Sets the value of the soaCommonResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOACommonResponse(String value) {
        this.soaCommonResponse = value;
    }

    /**
     * Gets the value of the soaFillers property.
     * 
     * @return
     *     possible object is
     *     {@link SoaFillers }
     *     
     */
    public SoaFillers getSoaFillers() {
        return soaFillers;
    }

    /**
     * Sets the value of the soaFillers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoaFillers }
     *     
     */
    public void setSoaFillers(SoaFillers value) {
        this.soaFillers = value;
    }

}
