//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.27 at 09:57:19 AM IST 
//


package hdfcbank.ws.dedupecheck;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hdfcbank.ws.dedupecheck package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hdfcbank.ws.dedupecheck
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnquiryServiceResponse }
     * 
     */
    public EnquiryServiceResponse createEnquiryServiceResponse() {
        return new EnquiryServiceResponse();
    }

    /**
     * Create an instance of {@link SoaFillers }
     * 
     */
    public SoaFillers createSoaFillers() {
        return new SoaFillers();
    }

    /**
     * Create an instance of {@link EnquiryServiceRequest }
     * 
     */
    public EnquiryServiceRequest createEnquiryServiceRequest() {
        return new EnquiryServiceRequest();
    }

    /**
     * Create an instance of {@link HeaderInfoType }
     * 
     */
    public HeaderInfoType createHeaderInfoType() {
        return new HeaderInfoType();
    }

    /**
     * Create an instance of {@link EnquiryInfoType }
     * 
     */
    public EnquiryInfoType createEnquiryInfoType() {
        return new EnquiryInfoType();
    }

    /**
     * Create an instance of {@link SoaStandard }
     * 
     */
    public SoaStandard createSoaStandard() {
        return new SoaStandard();
    }

    /**
     * Create an instance of {@link GetStatusRequest }
     * 
     */
    public GetStatusRequest createGetStatusRequest() {
        return new GetStatusRequest();
    }

    /**
     * Create an instance of {@link GetStatusServiceResponse }
     * 
     */
    public GetStatusServiceResponse createGetStatusServiceResponse() {
        return new GetStatusServiceResponse();
    }

    /**
     * Create an instance of {@link DedupeServiceRequest }
     * 
     */
    public DedupeServiceRequest createDedupeServiceRequest() {
        return new DedupeServiceRequest();
    }

    /**
     * Create an instance of {@link DedupeServiceResponse }
     * 
     */
    public DedupeServiceResponse createDedupeServiceResponse() {
        return new DedupeServiceResponse();
    }

    /**
     * Create an instance of {@link DedupeResponseHeaderInfoType }
     * 
     */
    public DedupeResponseHeaderInfoType createDedupeResponseHeaderInfoType() {
        return new DedupeResponseHeaderInfoType();
    }

    /**
     * Create an instance of {@link DedupeResponseEnquiryInfoType }
     * 
     */
    public DedupeResponseEnquiryInfoType createDedupeResponseEnquiryInfoType() {
        return new DedupeResponseEnquiryInfoType();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link NegativeListType }
     * 
     */
    public NegativeListType createNegativeListType() {
        return new NegativeListType();
    }

    /**
     * Create an instance of {@link ClosedAccSummaryType }
     * 
     */
    public ClosedAccSummaryType createClosedAccSummaryType() {
        return new ClosedAccSummaryType();
    }

    /**
     * Create an instance of {@link ClosedAccMatchType }
     * 
     */
    public ClosedAccMatchType createClosedAccMatchType() {
        return new ClosedAccMatchType();
    }

    /**
     * Create an instance of {@link ClosedAccDetailType }
     * 
     */
    public ClosedAccDetailType createClosedAccDetailType() {
        return new ClosedAccDetailType();
    }

    /**
     * Create an instance of {@link AddressesType }
     * 
     */
    public AddressesType createAddressesType() {
        return new AddressesType();
    }

    /**
     * Create an instance of {@link MatchParameterType }
     * 
     */
    public MatchParameterType createMatchParameterType() {
        return new MatchParameterType();
    }

    /**
     * Create an instance of {@link MatchValueType }
     * 
     */
    public MatchValueType createMatchValueType() {
        return new MatchValueType();
    }

}
