//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package com.hdfcbank.xsd.multibureau;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommunicationParamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommunicationParamType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AGGREGATOR_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="INSTITUTION_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MEMBER_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PASSWORD" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommunicationParamType", propOrder = {
    "aggregatorid",
    "institutionid",
    "memberid",
    "password"
})
public class CommunicationParamType {

    @XmlElement(name = "AGGREGATOR_ID", required = true)
    protected String aggregatorid;
    @XmlElement(name = "INSTITUTION_ID", required = true)
    protected String institutionid;
    @XmlElement(name = "MEMBER_ID", required = true)
    protected String memberid;
    @XmlElement(name = "PASSWORD", required = true)
    protected String password;

    /**
     * Gets the value of the aggregatorid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGGREGATORID() {
        return aggregatorid;
    }

    /**
     * Sets the value of the aggregatorid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGGREGATORID(String value) {
        this.aggregatorid = value;
    }

    /**
     * Gets the value of the institutionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSTITUTIONID() {
        return institutionid;
    }

    /**
     * Sets the value of the institutionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSTITUTIONID(String value) {
        this.institutionid = value;
    }

    /**
     * Gets the value of the memberid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMBERID() {
        return memberid;
    }

    /**
     * Sets the value of the memberid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMBERID(String value) {
        this.memberid = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPASSWORD() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPASSWORD(String value) {
        this.password = value;
    }

}
