//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package com.hdfcbank.xsd.multibureau;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CommunicationParam" type="{multibureau.xsd.hdfcbank.com}CommunicationParamType"/&gt;
 *         &lt;element name="ACKNOWLEDGEMENT" type="{multibureau.xsd.hdfcbank.com}AcknowledgementType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "communicationParam",
    "acknowledgement"
})
@XmlRootElement(name = "MultiBureauServiceResponse")
public class MultiBureauServiceResponse {

    @XmlElement(name = "CommunicationParam", required = true)
    protected CommunicationParamType communicationParam;
    @XmlElement(name = "ACKNOWLEDGEMENT", required = true)
    protected AcknowledgementType acknowledgement;

    /**
     * Gets the value of the communicationParam property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationParamType }
     *     
     */
    public CommunicationParamType getCommunicationParam() {
        return communicationParam;
    }

    /**
     * Sets the value of the communicationParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationParamType }
     *     
     */
    public void setCommunicationParam(CommunicationParamType value) {
        this.communicationParam = value;
    }

    /**
     * Gets the value of the acknowledgement property.
     * 
     * @return
     *     possible object is
     *     {@link AcknowledgementType }
     *     
     */
    public AcknowledgementType getACKNOWLEDGEMENT() {
        return acknowledgement;
    }

    /**
     * Sets the value of the acknowledgement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcknowledgementType }
     *     
     */
    public void setACKNOWLEDGEMENT(AcknowledgementType value) {
        this.acknowledgement = value;
    }

}
