//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package com.hdfcbank.xsd.multibureau;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hdfcbank.xsd.multibureau package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hdfcbank.xsd.multibureau
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MultiBureauServiceRequest }
     * 
     */
    public MultiBureauServiceRequest createMultiBureauServiceRequest() {
        return new MultiBureauServiceRequest();
    }

    /**
     * Create an instance of {@link CommunicationParamType }
     * 
     */
    public CommunicationParamType createCommunicationParamType() {
        return new CommunicationParamType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link SoaStandard }
     * 
     */
    public SoaStandard createSoaStandard() {
        return new SoaStandard();
    }

    /**
     * Create an instance of {@link SoaFillers }
     * 
     */
    public SoaFillers createSoaFillers() {
        return new SoaFillers();
    }

    /**
     * Create an instance of {@link MultiBureauServiceResponse }
     * 
     */
    public MultiBureauServiceResponse createMultiBureauServiceResponse() {
        return new MultiBureauServiceResponse();
    }

    /**
     * Create an instance of {@link AcknowledgementType }
     * 
     */
    public AcknowledgementType createAcknowledgementType() {
        return new AcknowledgementType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link RequestDataType }
     * 
     */
    public RequestDataType createRequestDataType() {
        return new RequestDataType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link AckHeaderType }
     * 
     */
    public AckHeaderType createAckHeaderType() {
        return new AckHeaderType();
    }

    /**
     * Create an instance of {@link WarningsType }
     * 
     */
    public WarningsType createWarningsType() {
        return new WarningsType();
    }

    /**
     * Create an instance of {@link ErrorsType }
     * 
     */
    public ErrorsType createErrorsType() {
        return new ErrorsType();
    }

}
