//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.27 at 09:57:19 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "multibureau.xsd.hdfcbank.com")
package com.hdfcbank.xsd.multibureau;
