//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package com.hdfcbank.xsd.multibureau;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhoneType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PHONE-TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PHONE-NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PHONE-EXTN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="STD-CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneType", propOrder = {
    "phonetype",
    "phonenumber",
    "phoneextn",
    "stdcode"
})
public class PhoneType {

    @XmlElement(name = "PHONE-TYPE")
    protected String phonetype;
    @XmlElement(name = "PHONE-NUMBER")
    protected String phonenumber;
    @XmlElement(name = "PHONE-EXTN")
    protected String phoneextn;
    @XmlElement(name = "STD-CODE")
    protected String stdcode;

    /**
     * Gets the value of the phonetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONETYPE() {
        return phonetype;
    }

    /**
     * Sets the value of the phonetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONETYPE(String value) {
        this.phonetype = value;
    }

    /**
     * Gets the value of the phonenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONENUMBER() {
        return phonenumber;
    }

    /**
     * Sets the value of the phonenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONENUMBER(String value) {
        this.phonenumber = value;
    }

    /**
     * Gets the value of the phoneextn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONEEXTN() {
        return phoneextn;
    }

    /**
     * Sets the value of the phoneextn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONEEXTN(String value) {
        this.phoneextn = value;
    }

    /**
     * Gets the value of the stdcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTDCODE() {
        return stdcode;
    }

    /**
     * Sets the value of the stdcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTDCODE(String value) {
        this.stdcode = value;
    }

}
