//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 12:37:40 PM IST 
//


package com.hdfcbank.xsd.multibureau;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FATHER-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SPOUSE-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MOTHER-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RELATION-TYPE-1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RELATION-TYPE-1-VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RELATION-TYPE-2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RELATION-TYPE-2-VALUE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KEY-PERSON-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KEY-PERSON-RELATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NOMINEE-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NOMINEE-RELATION-TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationType", propOrder = {
    "fathername",
    "spousename",
    "mothername",
    "relationtype1",
    "relationtype1VALUE",
    "relationtype2",
    "relationtype2VALUE",
    "keypersonname",
    "keypersonrelation",
    "nomineename",
    "nomineerelationtype"
})
public class RelationType {

    @XmlElement(name = "FATHER-NAME")
    protected String fathername;
    @XmlElement(name = "SPOUSE-NAME")
    protected String spousename;
    @XmlElement(name = "MOTHER-NAME")
    protected String mothername;
    @XmlElement(name = "RELATION-TYPE-1")
    protected String relationtype1;
    @XmlElement(name = "RELATION-TYPE-1-VALUE")
    protected String relationtype1VALUE;
    @XmlElement(name = "RELATION-TYPE-2")
    protected String relationtype2;
    @XmlElement(name = "RELATION-TYPE-2-VALUE")
    protected String relationtype2VALUE;
    @XmlElement(name = "KEY-PERSON-NAME")
    protected String keypersonname;
    @XmlElement(name = "KEY-PERSON-RELATION")
    protected String keypersonrelation;
    @XmlElement(name = "NOMINEE-NAME")
    protected String nomineename;
    @XmlElement(name = "NOMINEE-RELATION-TYPE")
    protected String nomineerelationtype;

    /**
     * Gets the value of the fathername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATHERNAME() {
        return fathername;
    }

    /**
     * Sets the value of the fathername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATHERNAME(String value) {
        this.fathername = value;
    }

    /**
     * Gets the value of the spousename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPOUSENAME() {
        return spousename;
    }

    /**
     * Sets the value of the spousename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPOUSENAME(String value) {
        this.spousename = value;
    }

    /**
     * Gets the value of the mothername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTHERNAME() {
        return mothername;
    }

    /**
     * Sets the value of the mothername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTHERNAME(String value) {
        this.mothername = value;
    }

    /**
     * Gets the value of the relationtype1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELATIONTYPE1() {
        return relationtype1;
    }

    /**
     * Sets the value of the relationtype1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELATIONTYPE1(String value) {
        this.relationtype1 = value;
    }

    /**
     * Gets the value of the relationtype1VALUE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELATIONTYPE1VALUE() {
        return relationtype1VALUE;
    }

    /**
     * Sets the value of the relationtype1VALUE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELATIONTYPE1VALUE(String value) {
        this.relationtype1VALUE = value;
    }

    /**
     * Gets the value of the relationtype2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELATIONTYPE2() {
        return relationtype2;
    }

    /**
     * Sets the value of the relationtype2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELATIONTYPE2(String value) {
        this.relationtype2 = value;
    }

    /**
     * Gets the value of the relationtype2VALUE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELATIONTYPE2VALUE() {
        return relationtype2VALUE;
    }

    /**
     * Sets the value of the relationtype2VALUE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELATIONTYPE2VALUE(String value) {
        this.relationtype2VALUE = value;
    }

    /**
     * Gets the value of the keypersonname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKEYPERSONNAME() {
        return keypersonname;
    }

    /**
     * Sets the value of the keypersonname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKEYPERSONNAME(String value) {
        this.keypersonname = value;
    }

    /**
     * Gets the value of the keypersonrelation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKEYPERSONRELATION() {
        return keypersonrelation;
    }

    /**
     * Sets the value of the keypersonrelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKEYPERSONRELATION(String value) {
        this.keypersonrelation = value;
    }

    /**
     * Gets the value of the nomineename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMINEENAME() {
        return nomineename;
    }

    /**
     * Sets the value of the nomineename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMINEENAME(String value) {
        this.nomineename = value;
    }

    /**
     * Gets the value of the nomineerelationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMINEERELATIONTYPE() {
        return nomineerelationtype;
    }

    /**
     * Sets the value of the nomineerelationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMINEERELATIONTYPE(String value) {
        this.nomineerelationtype = value;
    }

}
