//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 12:56:42 PM IST 
//


package com.hdfcbank.xsd.addmatch.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="return" type="{http://uidaiekyc.addMatch.xsd.hdfcbank.com}returnType"/&gt;
 *         &lt;element name="namePercentage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="addressPercentage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="equalityPercentage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="phonePercentage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="perStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "_return",
    "namePercentage",
    "addressPercentage",
    "equalityPercentage",
    "phonePercentage",
    "perStatus",
    "remarks"
})
@XmlRootElement(name = "doAddressMatchPercentageResponse")
public class DoAddressMatchPercentageResponse {

    @XmlElement(name = "return", required = true)
    protected ReturnType _return;
    @XmlElement(required = true)
    protected String namePercentage;
    @XmlElement(required = true)
    protected String addressPercentage;
    @XmlElement(required = true)
    protected String equalityPercentage;
    @XmlElement(required = true)
    protected String phonePercentage;
    @XmlElement(required = true)
    protected String perStatus;
    @XmlElement(required = true)
    protected String remarks;

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnType }
     *     
     */
    public ReturnType getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnType }
     *     
     */
    public void setReturn(ReturnType value) {
        this._return = value;
    }

    /**
     * Gets the value of the namePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePercentage() {
        return namePercentage;
    }

    /**
     * Sets the value of the namePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePercentage(String value) {
        this.namePercentage = value;
    }

    /**
     * Gets the value of the addressPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressPercentage() {
        return addressPercentage;
    }

    /**
     * Sets the value of the addressPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressPercentage(String value) {
        this.addressPercentage = value;
    }

    /**
     * Gets the value of the equalityPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqualityPercentage() {
        return equalityPercentage;
    }

    /**
     * Sets the value of the equalityPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqualityPercentage(String value) {
        this.equalityPercentage = value;
    }

    /**
     * Gets the value of the phonePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhonePercentage() {
        return phonePercentage;
    }

    /**
     * Sets the value of the phonePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhonePercentage(String value) {
        this.phonePercentage = value;
    }

    /**
     * Gets the value of the perStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerStatus() {
        return perStatus;
    }

    /**
     * Sets the value of the perStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerStatus(String value) {
        this.perStatus = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

}
