//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.28 at 12:56:42 PM IST 
//


package com.hdfcbank.xsd.addmatch.uidaiekyc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SessionContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SessionContext"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Bankcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Channel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="brnPostingDateText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="electronicJournalOperationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalBatchNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalSystemAuditTrailNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="localDateTimeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="originalReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="overridenWarnings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postingDateText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Servicecode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sessionTicket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="supervisorContext" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionBranch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Userid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="userReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="valueDateText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SessionContext", propOrder = {
    "bankcode",
    "channel",
    "brnPostingDateText",
    "electronicJournalOperationType",
    "externalBatchNumber",
    "externalSystemAuditTrailNumber",
    "localDateTimeText",
    "originalReferenceNo",
    "overridenWarnings",
    "postingDateText",
    "reason",
    "servicecode",
    "sessionTicket",
    "supervisorContext",
    "transactionBranch",
    "userid",
    "userReferenceNumber",
    "valueDateText"
})
public class SessionContext {

    @XmlElement(name = "Bankcode")
    protected String bankcode;
    @XmlElement(name = "Channel")
    protected String channel;
    protected String brnPostingDateText;
    protected String electronicJournalOperationType;
    protected String externalBatchNumber;
    protected String externalSystemAuditTrailNumber;
    protected String localDateTimeText;
    protected String originalReferenceNo;
    protected String overridenWarnings;
    protected String postingDateText;
    protected String reason;
    @XmlElement(name = "Servicecode")
    protected String servicecode;
    protected String sessionTicket;
    protected String supervisorContext;
    @XmlElement(name = "TransactionBranch")
    protected String transactionBranch;
    @XmlElement(name = "Userid")
    protected String userid;
    protected String userReferenceNumber;
    protected String valueDateText;

    /**
     * Gets the value of the bankcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * Sets the value of the bankcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankcode(String value) {
        this.bankcode = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the brnPostingDateText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrnPostingDateText() {
        return brnPostingDateText;
    }

    /**
     * Sets the value of the brnPostingDateText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrnPostingDateText(String value) {
        this.brnPostingDateText = value;
    }

    /**
     * Gets the value of the electronicJournalOperationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicJournalOperationType() {
        return electronicJournalOperationType;
    }

    /**
     * Sets the value of the electronicJournalOperationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicJournalOperationType(String value) {
        this.electronicJournalOperationType = value;
    }

    /**
     * Gets the value of the externalBatchNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalBatchNumber() {
        return externalBatchNumber;
    }

    /**
     * Sets the value of the externalBatchNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalBatchNumber(String value) {
        this.externalBatchNumber = value;
    }

    /**
     * Gets the value of the externalSystemAuditTrailNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalSystemAuditTrailNumber() {
        return externalSystemAuditTrailNumber;
    }

    /**
     * Sets the value of the externalSystemAuditTrailNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalSystemAuditTrailNumber(String value) {
        this.externalSystemAuditTrailNumber = value;
    }

    /**
     * Gets the value of the localDateTimeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalDateTimeText() {
        return localDateTimeText;
    }

    /**
     * Sets the value of the localDateTimeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalDateTimeText(String value) {
        this.localDateTimeText = value;
    }

    /**
     * Gets the value of the originalReferenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalReferenceNo() {
        return originalReferenceNo;
    }

    /**
     * Sets the value of the originalReferenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalReferenceNo(String value) {
        this.originalReferenceNo = value;
    }

    /**
     * Gets the value of the overridenWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverridenWarnings() {
        return overridenWarnings;
    }

    /**
     * Sets the value of the overridenWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverridenWarnings(String value) {
        this.overridenWarnings = value;
    }

    /**
     * Gets the value of the postingDateText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingDateText() {
        return postingDateText;
    }

    /**
     * Sets the value of the postingDateText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingDateText(String value) {
        this.postingDateText = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the servicecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicecode() {
        return servicecode;
    }

    /**
     * Sets the value of the servicecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicecode(String value) {
        this.servicecode = value;
    }

    /**
     * Gets the value of the sessionTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionTicket() {
        return sessionTicket;
    }

    /**
     * Sets the value of the sessionTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionTicket(String value) {
        this.sessionTicket = value;
    }

    /**
     * Gets the value of the supervisorContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisorContext() {
        return supervisorContext;
    }

    /**
     * Sets the value of the supervisorContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisorContext(String value) {
        this.supervisorContext = value;
    }

    /**
     * Gets the value of the transactionBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionBranch() {
        return transactionBranch;
    }

    /**
     * Sets the value of the transactionBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionBranch(String value) {
        this.transactionBranch = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserid(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the userReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReferenceNumber() {
        return userReferenceNumber;
    }

    /**
     * Sets the value of the userReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReferenceNumber(String value) {
        this.userReferenceNumber = value;
    }

    /**
     * Gets the value of the valueDateText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDateText() {
        return valueDateText;
    }

    /**
     * Sets the value of the valueDateText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDateText(String value) {
        this.valueDateText = value;
    }

}
