//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.30 at 12:15:01 AM IST 
//


package com.hdfcbank.smsservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ctype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mobilenumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="msgtxt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="departmentcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="submitdate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subAuthor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="broadcastname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="internationalflag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="msgid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="drlflag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dndalert" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="msgtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_4" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_5" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "userid",
    "password",
    "ctype",
    "sender",
    "mobilenumber",
    "msgtxt",
    "departmentcode",
    "submitdate",
    "author",
    "subAuthor",
    "broadcastname",
    "internationalflag",
    "msgid",
    "drlflag",
    "dndalert",
    "msgtype",
    "priority",
    "filler1",
    "filler2",
    "filler3",
    "filler4",
    "filler5"
})
public class RequestType {

    @XmlElement(required = true)
    protected String userid;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String ctype;
    @XmlElement(required = true)
    protected String sender;
    @XmlElement(required = true)
    protected String mobilenumber;
    @XmlElement(required = true)
    protected String msgtxt;
    @XmlElement(required = true)
    protected String departmentcode;
    @XmlElement(required = true)
    protected String submitdate;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String subAuthor;
    @XmlElement(required = true)
    protected String broadcastname;
    @XmlElement(required = true)
    protected String internationalflag;
    @XmlElement(required = true)
    protected String msgid;
    @XmlElement(required = true)
    protected String drlflag;
    @XmlElement(required = true)
    protected String dndalert;
    @XmlElement(required = true)
    protected String msgtype;
    @XmlElement(required = true)
    protected String priority;
    @XmlElement(name = "filler_1", required = true)
    protected String filler1;
    @XmlElement(name = "filler_2", required = true)
    protected String filler2;
    @XmlElement(name = "filler_3", required = true)
    protected String filler3;
    @XmlElement(name = "filler_4", required = true)
    protected String filler4;
    @XmlElement(name = "filler_5", required = true)
    protected String filler5;

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserid(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the ctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtype() {
        return ctype;
    }

    /**
     * Sets the value of the ctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtype(String value) {
        this.ctype = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSender(String value) {
        this.sender = value;
    }

    /**
     * Gets the value of the mobilenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilenumber() {
        return mobilenumber;
    }

    /**
     * Sets the value of the mobilenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilenumber(String value) {
        this.mobilenumber = value;
    }

    /**
     * Gets the value of the msgtxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgtxt() {
        return msgtxt;
    }

    /**
     * Sets the value of the msgtxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgtxt(String value) {
        this.msgtxt = value;
    }

    /**
     * Gets the value of the departmentcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentcode() {
        return departmentcode;
    }

    /**
     * Sets the value of the departmentcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentcode(String value) {
        this.departmentcode = value;
    }

    /**
     * Gets the value of the submitdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitdate() {
        return submitdate;
    }

    /**
     * Sets the value of the submitdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitdate(String value) {
        this.submitdate = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the subAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubAuthor() {
        return subAuthor;
    }

    /**
     * Sets the value of the subAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubAuthor(String value) {
        this.subAuthor = value;
    }

    /**
     * Gets the value of the broadcastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroadcastname() {
        return broadcastname;
    }

    /**
     * Sets the value of the broadcastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroadcastname(String value) {
        this.broadcastname = value;
    }

    /**
     * Gets the value of the internationalflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalflag() {
        return internationalflag;
    }

    /**
     * Sets the value of the internationalflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalflag(String value) {
        this.internationalflag = value;
    }

    /**
     * Gets the value of the msgid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * Sets the value of the msgid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgid(String value) {
        this.msgid = value;
    }

    /**
     * Gets the value of the drlflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrlflag() {
        return drlflag;
    }

    /**
     * Sets the value of the drlflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrlflag(String value) {
        this.drlflag = value;
    }

    /**
     * Gets the value of the dndalert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDndalert() {
        return dndalert;
    }

    /**
     * Sets the value of the dndalert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDndalert(String value) {
        this.dndalert = value;
    }

    /**
     * Gets the value of the msgtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * Sets the value of the msgtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgtype(String value) {
        this.msgtype = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the filler1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller1() {
        return filler1;
    }

    /**
     * Sets the value of the filler1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller1(String value) {
        this.filler1 = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller2(String value) {
        this.filler2 = value;
    }

    /**
     * Gets the value of the filler3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * Sets the value of the filler3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller3(String value) {
        this.filler3 = value;
    }

    /**
     * Gets the value of the filler4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller4() {
        return filler4;
    }

    /**
     * Sets the value of the filler4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller4(String value) {
        this.filler4 = value;
    }

    /**
     * Gets the value of the filler5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller5() {
        return filler5;
    }

    /**
     * Sets the value of the filler5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller5(String value) {
        this.filler5 = value;
    }

}
