//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.11 at 09:53:34 AM IST 
//


package com.hdfcbank.smsservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="responsecode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_4" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="filler_5" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responsecode",
    "message",
    "filler1",
    "filler2",
    "filler3",
    "filler4",
    "filler5"
})
@XmlRootElement(name = "SMSResponse")
public class SMSResponse {

    @XmlElement(required = true)
    protected String responsecode;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(name = "filler_1", required = true)
    protected String filler1;
    @XmlElement(name = "filler_2", required = true)
    protected String filler2;
    @XmlElement(name = "filler_3", required = true)
    protected String filler3;
    @XmlElement(name = "filler_4", required = true)
    protected String filler4;
    @XmlElement(name = "filler_5", required = true)
    protected String filler5;

    /**
     * Gets the value of the responsecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsecode() {
        return responsecode;
    }

    /**
     * Sets the value of the responsecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsecode(String value) {
        this.responsecode = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the filler1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller1() {
        return filler1;
    }

    /**
     * Sets the value of the filler1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller1(String value) {
        this.filler1 = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller2(String value) {
        this.filler2 = value;
    }

    /**
     * Gets the value of the filler3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * Sets the value of the filler3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller3(String value) {
        this.filler3 = value;
    }

    /**
     * Gets the value of the filler4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller4() {
        return filler4;
    }

    /**
     * Sets the value of the filler4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller4(String value) {
        this.filler4 = value;
    }

    /**
     * Gets the value of the filler5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller5() {
        return filler5;
    }

    /**
     * Sets the value of the filler5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller5(String value) {
        this.filler5 = value;
    }

}
